Repository cloudify-cosmo/cloudify-terraform-plugin, pull requests merged in 2022-07, with the labels that each got.

#194 RD-5011-Infracost-Support
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/infracost.py
  cloudify_tf/workflows.py
  plugin.yaml
  v2_plugin.yaml
Labels: Experimental

#199 Rd 4717 hide secrets
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/tests/__init__.py
  cloudify_tf/tests/test_plugin.py
  cloudify_tf/utils.py
  setup.py
  test-requirements.txt
Labels: bug

#197 RD-5146-update-manager-orb-to-use-6-4-dev-build
  .circleci/config.yml
Labels: bug

#200 Rd 5347 better handle local archive
  CHANGELOG.txt
  cloudify_tf/utils.py
Labels: bug

#207 0.19.0 build
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/infracost.py
  cloudify_tf/utils.py
  plugin.yaml
  plugin_1_4.yaml
  setup.py
  test-requirements.txt
  v2_plugin.yaml
Labels: core
