Repository cloudify-cosmo/cloudify-terraform-plugin, pull requests merged in 2022-02, with the labels that each got.

#124 update terraform binary
  .circleci/config.yml
  plugin.yaml
Labels: bug

#127 orb update
  .circleci/config.yml
Labels: bug

#123 update plugin YAML for TFlint
  .gitignore
  CHANGELOG.txt
  README.md
  blueprints/blueprint.yaml
  cloudify_tf/constants.py
  cloudify_tf/decorators.py
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/tests/__init__.py
  cloudify_tf/terraform/tests/resources/resources.zip
  cloudify_tf/terraform/tests/resources/tflint-mock
  cloudify_tf/terraform/tests/test_tflint_tool.py
  cloudify_tf/terraform/tests/test_tools_base.py
  cloudify_tf/terraform/tflint.py
  cloudify_tf/terraform/tools_base.py
  cloudify_tf/tests/test_plugin.py
  cloudify_tf/tests/test_utils.py
  cloudify_tf/utils.py
  constraints.txt
  plugin.yaml
  setup.py
  test-requirements.txt
  tox.ini
Labels: good first issue

#132 fix small bug
  cloudify_tf/terraform/__init__.py
Labels: bug

#135 try this
  .circleci/config.yml
Labels: bug

#137 build that
  cloudify_tf/tasks.py
  cloudify_tf/tests/__init__.py
  cloudify_tf/tests/test_plugin.py
  plugin.yaml
Labels: Experimental

#140 Rd 4036 2 jason
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  plugin.yaml
Labels: bug

#134 RD-4013-support-lifecycle-management-of-tf-sec-binary
  CHANGELOG.txt
  cloudify_tf/terraform/tests/test_tfsec.py
  cloudify_tf/terraform/tests/test_tools_base.py
  cloudify_tf/terraform/tfsec.py
  cloudify_tf/terraform/tools_base.py
  plugin.yaml
Labels: bug

#139 Rd 4016 examples and integration tests to use the tfsec
  cloudify_tf/decorators.py
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/tfsec.py
  cloudify_tf/terraform/tools_base.py
  cloudify_tf/tests/test_plugin.py
  constraints.txt
  plugin.yaml
  setup.py
Labels: Experimental

#148 Intermediate release
  CHANGELOG.txt
  plugin.yaml
Labels: bug

#147 Rd 4261 clone cloudify terraform plugin quiet mode
  CHANGELOG.txt
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/tests/test_tflint_tool.py
  cloudify_tf/terraform/tests/test_tfsec.py
  cloudify_tf/terraform/tests/test_tools_base.py
  cloudify_tf/terraform/tools_base.py
  cloudify_tf/tests/test_plugin.py
  plugin.yaml
Labels: bug
