Repository cloudify-cosmo/cloudify-terraform-plugin, pull requests merged in 2022-04, with the labels that each got.

#158 RD-4693-Add-Import-Resource
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/tests/test_plugin.py
  cloudify_tf/workflows.py
  plugin.yaml
Labels: Experimental

#159 fix update version issue
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/terratag.py
  cloudify_tf/utils.py
  cloudify_tf/workflows.py
  plugin.yaml
Labels: Experimental

#161 0.18.16 build
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/terratag.py
  cloudify_tf/tests/test_plugin.py
  cloudify_tf/utils.py
  cloudify_tf/workflows.py
  plugin.yaml
Labels: Experimental

#164 RD-4653-support-tf-vars
  CHANGELOG.txt
  cloudify_tf/decorators.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/tests/test_plugin.py
  plugin.yaml
Labels: enhancement

#166 Don't-Override-With-Empty-Kwargs
  cloudify_tf/terraform/__init__.py
Labels: bug

#170 handle file system issues
  CHANGELOG.txt
  cloudify_tf/terraform/__init__.py
  cloudify_tf/utils.py
  plugin.yaml
Labels: bug

#171 Handle-intrinsic-functions
  CHANGELOG.txt
  cloudify_tf/tasks.py
  cloudify_tf/terraform/__init__.py
  cloudify_tf/terraform/tests/test_tflint_tool.py
  cloudify_tf/terraform/tests/test_tools_base.py
  cloudify_tf/utils.py
Labels: bug
